# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2.1

jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "8.3.3"

    steps:
      - checkout

      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            pod install --project-directory=Example

      # Lint Podfile
      - run:
          name: Lint Podfile
          command: pod lib lint --allow-warnings

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: fastlane scan --workspace "Example/Castle.xcworkspace" --code_coverage
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: Castle-Example

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: build/reports
      - run: bash <(curl -s https://codecov.io/bash)

      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

