# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.3
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "8.3.3"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output

    steps:
      - checkout

      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            pod install --project-directory=Example

      # Lint Podfile
      - run:
          name: Lint Podfile
          command: pod lib lint --allow-warnings

      # Build the app and run tests
      - run:
          name: Run tests
          command: fastlane scan --workspace "Example/Castle.xcworkspace" --code_coverage
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: Castle-Example

      - store_test_results:
          path: output/scan

      - store_artifacts:
          path: output

      - codecov/upload:
          file: output/report.junit

